"""added true to cert

Revision ID: 10cc5c86f9a7
Revises: 19d0e2e1600a
Create Date: 2026-01-12 15:28:41.908394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10cc5c86f9a7'
down_revision = '19d0e2e1600a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('certificate',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('certificate',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
