"""new update

Revision ID: 12022c798998
Revises: 69d8b38760f4
Create Date: 2026-01-15 17:46:34.686543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12022c798998'
down_revision = '69d8b38760f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('cv',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('cv',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###
