"""added new profile to user

Revision ID: 13c8c72093cb
Revises: b745c57cb7c8
Create Date: 2025-12-02 10:31:01.373254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c8c72093cb'
down_revision = 'b745c57cb7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documents', sa.String(length=255), nullable=True))
        batch_op.drop_column('cv_file')
        batch_op.drop_column('certificate_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cv_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('documents')

    # ### end Alembic commands ###
