"""create at

Revision ID: 19d0e2e1600a
Revises: 59a762a61568
Create Date: 2026-01-07 17:34:41.246736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d0e2e1600a'
down_revision = '59a762a61568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_subscriber', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
