"""admin email verification

Revision ID: 1a4dfd501671
Revises: 
Create Date: 2025-11-28 23:54:53.043757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4dfd501671'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###

    with op.batch_alter_table('admin', schema=None) as batch_op:
        # Add column with server_default to satisfy NOT NULL constraint
        batch_op.add_column(sa.Column('fullname', sa.String(length=150), nullable=False, server_default='Admin'))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('admin_username_key', type_='unique')
        batch_op.drop_column('username')
        # Remove default for future inserts
        batch_op.alter_column('fullname', server_default=None)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=150), nullable=False, server_default='User'))
        batch_op.drop_column('username')
        batch_op.alter_column('fullname', server_default=None)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('fullname')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('admin_username_key', ['username'])
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp_code')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
