"""added activate and deactivate route

Revision ID: 2b35a0b9f0d9
Revises: 37933028d7f7
Create Date: 2025-12-24 11:59:54.809989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b35a0b9f0d9'
down_revision = '37933028d7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('subject', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.drop_column('subject')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
