"""updated the user model

Revision ID: 3589a62f91d4
Revises: 13c8c72093cb
Create Date: 2025-12-07 04:29:39.992501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3589a62f91d4'
down_revision = '13c8c72093cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('certificate', sa.String(length=255), nullable=True))
        batch_op.drop_column('documents')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documents', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('certificate')
        batch_op.drop_column('cv')

    # ### end Alembic commands ###
