"""neww update

Revision ID: 59a762a61568
Revises: 6e96774ebf18
Create Date: 2026-01-07 03:10:55.901670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59a762a61568'
down_revision = '6e96774ebf18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('added_on')

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('external_subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('subscribed_at')

    # ### end Alembic commands ###
