"""added new profile to user

Revision ID: b745c57cb7c8
Revises: 65c8909bb4f6
Create Date: 2025-12-02 10:03:54.624256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b745c57cb7c8'
down_revision = '65c8909bb4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('other_names', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ghana_card_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('preferred_subject', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('preferred_level', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('cv_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('certificate_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('certificate_file')
        batch_op.drop_column('cv_file')
        batch_op.drop_column('preferred_level')
        batch_op.drop_column('preferred_subject')
        batch_op.drop_column('ghana_card_number')
        batch_op.drop_column('phone')
        batch_op.drop_column('other_names')
        batch_op.drop_column('surname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
