"""add location to job post

Revision ID: c2d3e4f5g6h7
Revises: fbbca0f9a5da
Create Date: 2026-05-08 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d3e4f5g6h7'
down_revision = 'fbbca0f9a5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False, server_default='Unknown'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
