"""new model update

Revision ID: d4de7cc20bec
Revises: 3589a62f91d4
Create Date: 2025-12-10 09:01:53.417239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4de7cc20bec'
down_revision = '3589a62f91d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bookshop_image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('bookshop_image_url')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
