"""added phone field

Revision ID: f3baa97e37ae
Revises: 2b35a0b9f0d9
Create Date: 2025-12-24 14:43:23.735063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3baa97e37ae'
down_revision = '2b35a0b9f0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_order', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
