"""updated  order model

Revision ID: fbbca0f9a5da
Revises: d4de7cc20bec
Create Date: 2025-12-16 19:12:21.159753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbca0f9a5da'
down_revision = 'd4de7cc20bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
