"""updated product

Revision ID: 0d73ad6bdd72
Revises: ddaa29bba2ed
Create Date: 2025-06-29 18:29:16.597207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d73ad6bdd72'
down_revision = 'ddaa29bba2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('brand')
        batch_op.drop_column('subject')
        batch_op.drop_column('level')
        batch_op.drop_column('grade')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
