"""changed int to string

Revision ID: 3dc68bc92c04
Revises: d37418765bd4
Create Date: 2025-07-08 10:13:24.936110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc68bc92c04'
down_revision = 'd37418765bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_order', schema=None) as batch_op:
        batch_op.alter_column('original_order_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_order', schema=None) as batch_op:
        batch_op.alter_column('original_order_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
