"""migrating gallery

Revision ID: 68c565f7ebee
Revises: 74de613bb67c
Create Date: 2025-06-17 18:22:00.899888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c565f7ebee'
down_revision = '74de613bb67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=True))
        batch_op.drop_column('uploaded_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###
