"""added some routes to admin model

Revision ID: 84e6c1b95ae4
Revises: 68c565f7ebee
Create Date: 2025-06-21 08:07:57.358002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e6c1b95ae4'
down_revision = '68c565f7ebee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_stock', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('in_stock')

    # ### end Alembic commands ###
