"""updated

Revision ID: 9af222d6f8ab
Revises: 84e6c1b95ae4
Create Date: 2025-06-21 07:50:57.271174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af222d6f8ab'
down_revision = '84e6c1b95ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecommerce_product_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('ecommerce_product_id')

    # ### end Alembic commands ###
