"""added category model

Revision ID: ddaa29bba2ed
Revises: 9af222d6f8ab
Create Date: 2025-06-24 10:23:27.505637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddaa29bba2ed'
down_revision = '9af222d6f8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key( 'fk_product_category_id',   # 👈 give the foreign key a name
            'category',                 # referenced table
            ['category_id'],            # local column
            ['id'] )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
