"""added date receieved to model

Revision ID: ece9f0c2941d
Revises: 460cc729457c
Create Date: 2025-06-29 18:03:37.707207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece9f0c2941d'
down_revision = '460cc729457c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_received', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_order', schema=None) as batch_op:
        batch_op.drop_column('date_received')

    # ### end Alembic commands ###
